name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Login to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Build and push the Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker           # points to /docker folder
          file: ./docker/Dockerfile   # explicit Dockerfile path
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frigate-smtp:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/frigate-smtp:${{ github.sha }}
